# Generated by Django 4.1.7 on 2023-02-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=10)),
                ('isbn', models.CharField(max_length=10)),
            ],
        ),
    ]
